title: HOSPITAL BLANES
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://xadouuu7.github.io/hospital/

plugins:
  - jekyll-default-layout