INSERT INTO material_quirofano VALUES
	('Mesa quirúrgica general'),
	('Mesa quirúrgica ortopédica'),
	('Mesa quirúrgica para cirugía de columna'),
	('Mesa quirúrgica para cirugía laparoscópica'),
	('Mesa quirúrgica para cirugía cardíaca'),
	('Lámparas de luz fría'),
	('Lámparas de LED'),
	('Lámparas de fluorescencia'),
	('Lámparas de doble cabezal'),
	('Lámparas portátiles'),
	('Monitor de signos vitales multiparamétrico'),
	('Monitor de presión arterial invasiva'),
	('Monitor de electrocardiograma'),
	('Monitor de saturación de oxígeno'),
	('Monitor de temperatura'),
	('Maquina de anestesia'),
	('Sistema de ventilación mecánica'),
	('Bombas de infusión volumétricas'),
	('Bombas de infusión de jeringa'),
	('Bombas de infusión de perfusión continua'),
	('Bombas de infusión PCA'),
	('Bombas de infusión enteral'),
	('Sistema de aspiración'),
	('Pinza de disección'),
	('Pinza de sutura'),
	('Pinza hemostáticas'),
	('Pinza de tejido'),
	('Tijeras rectas'),
	('Tijeras curvas'),
	('Tijeras de disección'),
	('Bisturí'),
	('Separador manual'),
	('Separador autónomo'),
	('Retractor manual'),
	('Retractor de gancho'),
	('Retractor autoajustable'),
	('Portaagujas'),
	('Cánula de aspiración'),
	('Cánula de drenaje'),
	('Cánula de irrigación'),
	('Fórceps'),
	('Equipo de esterilización'),
	('Sistema de videoendoscopia'),
	('Bata quirúrgica'),
	('Gorro quirúrgico'),
	('Mascarilla quirúrgica'),
	('Guantes quirúrgicos'),
	('Cubrezapatos'),
	('Algodón'),
	('Vendajes'),
	('Alcohol de 96º'),
	('Alcohol de 70º'),
	('Yodo'),
	('Tijera Bruns'),
	('Pinza adson'),
	('Puntos de aproximación'),
	('Seda para sutura'),
	('Gasa estéril'),
	('Esparadrapo'),
	('Tirita adhesiva'),
	('Banda elástica'),
	('Férula'),
	('Toallita desinfectante'),
	('Toallita impregnada en alcohol'),
	('Imperdible'),
	('Guantes de látex estériles'),
	('Guantes sin látex estériles'),
	('Mascarilla de RCP');