INSERT INTO material_general VALUES
	('Pinza Hartmann'),
	('Pinza Hartmann Cocodrilo'),
	('Abre-bocas Doyen'),
	('Jeringa para lavado de oído'),
	('Espéculo Hartmann'),
	('Espéculo Tieck-Halle infantil'),
	('Espéculo'),
	('Espéculo Killian'),
	('Depresor de lengua'),
	('Tijera recta Roma/Roma'),
	('Tijera recta Aguda/Aguda'),
	('Tijera recta Aguda/Roma'),
	('Tijera curva Roma/Roma'),
	('Peso clínico'),
	('Tallímetro'),
	('Negatoscopio'),
	('Otoscopio'),
	('Rinoscopio'),
	('Oftalmoscopio'),
	('Fonendoscopio'),
	('Esfigmomanómetro'),
	('Termometro'),
	('Camilla de exploración'),
	('Electrocardiógrafo'),
	('Equipo de reanimación cardiopulmonar'),
	('Linterna'),
	('Martillo de reflejos'),
	('Espirómetro'),
	('Neumotacógrafo'),
	('Equipo para control visión'),
	('Audiómetro'),
	('Contenedor de residuos sanitarios'),
	('Aguja hipodérmica'),
	('Jeringa'),
	('Seda para sutura'),
	('Gasa estéril'),
	('Esparadrapo'),
	('Tirita adhesiva'),
	('Banda elástica'),
	('Férula'),
	('Toallita desinfectante'),
	('Toallita impregnada en alcohol'),
	('Imperdible'),
	('guantes de látex estériles'),
	('guantes sin látex estériles'),
	('Mascarilla de RCP'),
	('tensiómetro'),
	('pulsioxímetro'),
	('Algodón'),
	('Vendajes'),
	('Papel camilla'),
	('Agua oxigenada'),
	('Alcohol de 96º'),
	('Alcohol de 70º'),
	('Yodo'),
	('Tijera Bruns'),
	('Pinza adson'),
	('Puntos de aproximación'),
	('Mascarilla quirúrgica'),
	('Mascarilla de protección autofiltrante FFP1'),
	('Mascarilla de protección autofiltrante FFP2'),
	('Mascarilla de protección autofiltrante FFP3'),
	('Mascarilla de protección con filtros de partículas'),
	('Filtro P1'),
	('Filtro P2'),
	('Filtro P3');