INSERT INTO material_laboratorio VALUES 
	('Probeta graduada'),
	('Pipeta'),
	('Bureta'),
	('Embudo'),
	('Vaso de precipitado'),
	('Cristalizadores'),
	('Vidrio de Reloj'),
	('Desecador'),
	('Caja de Petri'),
	('Varilla'),
	('Frasco Gotero'),
	('Lámpara de alcohol'),
	('Tubos de ensayo'),
	('Balón de destilación'),
	('Portaobjectos'),
	('Placa excavada'),
	('Pesafiltros'),
	('Tubo refrigerante'),
	('Triángulo de cristal'),
	('Matraz Morado'),
	('Matraz Erlenmeyer'),
	('Matraz Kitasato'),
	('Matraz Florentino'),
	('Matraz Le Chatelier'),
	('Matraz de Florencia'),
	('Piseta'),
	('Propipeta'),
	('Matraz con filtro brazo lateral'),
	('Jarra graduada'),
	('Jeringa'),
	('Cámara de Neubauer'),
	('Aspirador de Cremallera'),
	('Tapones'),
	('Vaso precipitado de plástico'),
	('Pinzas de madera'),
	('Gradilla'),
	('Soporte universal'),
	('Trípode'),
	('Mechero de Bunsen'),
	('Bisturí'),
	('Doble nuez'),
	('Espátula'),
	('Agua de disección'),
	('Aros de metal'),
	('Gradillas'),
	('Rejilla de Asbesto'),
	('Sacabocados'),
	('Mechero de Fisher'),
	('Pinza de Hoffman'),
	('Pinzas de sujeción'),
	('Pinzas dobles para bureta'),
	('Pinzas Mohr'),
	('Pinzas para vaso de precipitado'),
	('Agarradera'),
	('Asa bacteriológica'),
	('Charola de disección'),
	('Cápsula de porcelana'),
	('Crisol'),
	('Navecilla'),
	('Cinta métrica'),
	('Probeta'),
	('Calibre'),
	('Densímetro'),
	('Regla'),
	('Escobilla'),
	('Filtro pegado'),
	('Goma de conexión'),
	('Baño maría'),
	('Baño seco'),
	('Estufa bacteriológica'),
	('Horno eléctrico'),
	('Autoclave'),
	('Mufla'),
	('Contador de colonias'),
	('Centrífuga'),
	('Microcentrífuga'),
	('Centrífuga eléctrica sero-fuge'),
	('Agitador de pipetas Thoma'),
	('Agitador de Mazzini'),
	('Agitador de placas'),
	('Agitador de tubos'),
	('Balanza granataria'),
	('Balanza analítica eléctrica'),
	('Balanza analítica digital'),
	('Papel pH'),
	('Medidor de pH'),
	('Aerómetro'),
	('Picnómetro'),
	('Termómetro'),
	('Microscopio');